<a href="https://colab.research.google.com/github/manu93jadon/CI-CD-Project/blob/master/IPL_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Download dataset and load in df

In [285]:
import pandas as pd
import urllib.request
url = 'https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/158/850/original/IPL_2008-2024.csv?1760202529'
output_file = 'ipldata.csv'

# Download the file
urllib.request.urlretrieve(url, output_file)
print(f"Downloaded data to {output_file}")

ipl_df = pd.read_csv(output_file)

Downloaded data to ipldata.csv

#Import Section

In [286]:
import numpy as np

# 1 ) Data Preprocessing & Feature Engineering
Prepare the IPL dataset through cleaning, exploratory analysis, and creation of meaningful new features that capture match dynamics.

In [287]:
ipl_df.shape

(1095, 20)

In [288]:
ipl_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   int64
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(2), object(15)
memory usage: 171.2+ KB

In [289]:
ipl_df.describe()

                 id       season  result_margin  target_runs  target_overs
count  1.095000e+03  1095.000000    1076.000000  1092.000000   1092.000000
mean   9.048283e+05  2016.126027      17.259294   165.684066     19.759341
std    3.677402e+05     4.946940      21.787444    33.427048      1.581108
min    3.359820e+05  2008.000000       1.000000    43.000000      5.000000
25%    5.483315e+05  2012.000000       6.000000   146.000000     20.000000
50%    9.809610e+05  2016.000000       8.000000   166.000000     20.000000
75%    1.254062e+06  2021.000000      20.000000   187.000000     20.000000
max    1.426312e+06  2024.000000     146.000000   288.000000     20.000000

In [290]:
# Check for missing values in each column
missing_values=ipl_df.isnull().sum().sort_values(ascending=False)
print(missing_values)

method             1074
city                 51
result_margin        19
player_of_match       5
winner                5
target_runs           3
target_overs          3
id                    0
date                  0
season                0
venue                 0
match_type            0
toss_decision         0
toss_winner           0
team2                 0
team1                 0
result                0
super_over            0
umpire1               0
umpire2               0
dtype: int64

In [291]:
#Check for unique values in each column
unique_values=ipl_df.nunique().sort_values(ascending=False)
print(unique_values)

id                 1095
date                823
player_of_match     291
target_runs         170
result_margin        98
umpire1              62
umpire2              62
venue                58
city                 36
toss_winner          19
team1                19
team2                19
winner               19
season               17
target_overs         15
match_type            8
result                4
toss_decision         2
super_over            2
method                1
dtype: int64

In [292]:
ipl_df.value_counts("venue")

venue
Eden Gardens                                                             77
Wankhede Stadium                                                         73
M Chinnaswamy Stadium                                                    65
Feroz Shah Kotla                                                         60
Rajiv Gandhi International Stadium, Uppal                                49
MA Chidambaram Stadium, Chepauk                                          48
Sawai Mansingh Stadium                                                   47
Dubai International Cricket Stadium                                      46
Wankhede Stadium, Mumbai                                                 45
Punjab Cricket Association Stadium, Mohali                               35
Sheikh Zayed Stadium                                                     29
MA Chidambaram Stadium, Chepauk, Chennai                                 28
Sharjah Cricket Stadium                                                  28
Narendra Modi Stadium, Ahmedabad                                         24
Maharashtra Cricket Association Stadium                                  22
Dr DY Patil Sports Academy, Mumbai                                       20
Dr DY Patil Sports Academy                                               17
Brabourne Stadium, Mumbai                                                17
Subrata Roy Sahara Stadium                                               16
Arun Jaitley Stadium, Delhi                                              16
Eden Gardens, Kolkata                                                    16
Rajiv Gandhi International Stadium                                       15
M.Chinnaswamy Stadium                                                    15
Kingsmead                                                                15
Arun Jaitley Stadium                                                     14
M Chinnaswamy Stadium, Bengaluru                                         14
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow    14
Rajiv Gandhi International Stadium, Uppal, Hyderabad                     13
Maharashtra Cricket Association Stadium, Pune                            13
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                      13
Sardar Patel Stadium, Motera                                             12
SuperSport Park                                                          12
Punjab Cricket Association IS Bindra Stadium, Mohali                     11
Saurashtra Cricket Association Stadium                                   10
Punjab Cricket Association IS Bindra Stadium                             10
Sawai Mansingh Stadium, Jaipur                                           10
Brabourne Stadium                                                        10
Holkar Cricket Stadium                                                    9
Himachal Pradesh Cricket Association Stadium                              9
MA Chidambaram Stadium                                                    9
Zayed Cricket Stadium, Abu Dhabi                                          8
New Wanderers Stadium                                                     8
Newlands                                                                  7
St George's Park                                                          7
Barabati Stadium                                                          7
JSCA International Stadium Complex                                        7
Shaheed Veer Narayan Singh International Stadium                          6
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh          5
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur        5
Nehru Stadium                                                             5
Green Park                                                                4
Himachal Pradesh Cricket Association Stadium, Dharamsala                  4
Buffalo Park                                                              3
De Beers Diamond Oval                                                     3
Vidarbha Cricket Association Stadium, Jamtha                              3
Barsapara Cricket Stadium, Guwahati                                       3
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam        2
OUTsurance Oval                                                           2
Name: count, dtype: int64

In [293]:
#Checking city along with Venue to confirm if some venue names are duplicated here
ipl_df.groupby("venue")["city"].value_counts("venue").sort_values(ascending=False)

venue                                                                  city
Arun Jaitley Stadium                                                   Delhi             1.00
Arun Jaitley Stadium, Delhi                                            Delhi             1.00
Barabati Stadium                                                       Cuttack           1.00
Barsapara Cricket Stadium, Guwahati                                    Guwahati          1.00
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow  Lucknow           1.00
Brabourne Stadium                                                      Mumbai            1.00
Brabourne Stadium, Mumbai                                              Mumbai            1.00
Buffalo Park                                                           East London       1.00
De Beers Diamond Oval                                                  Kimberley         1.00
Dr DY Patil Sports Academy                                             Mumbai            1.00
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                    Visakhapatnam     1.00
Kingsmead                                                              Durban            1.00
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam     Visakhapatnam     1.00
Dubai International Cricket Stadium                                    Dubai             1.00
Eden Gardens                                                           Kolkata           1.00
Feroz Shah Kotla                                                       Delhi             1.00
Eden Gardens, Kolkata                                                  Kolkata           1.00
Green Park                                                             Kanpur            1.00
Himachal Pradesh Cricket Association Stadium                           Dharamsala        1.00
M Chinnaswamy Stadium, Bengaluru                                       Bengaluru         1.00
Himachal Pradesh Cricket Association Stadium, Dharamsala               Dharamsala        1.00
Holkar Cricket Stadium                                                 Indore            1.00
JSCA International Stadium Complex                                     Ranchi            1.00
M.Chinnaswamy Stadium                                                  Bengaluru         1.00
M Chinnaswamy Stadium                                                  Bangalore         1.00
MA Chidambaram Stadium, Chepauk                                        Chennai           1.00
MA Chidambaram Stadium                                                 Chennai           1.00
Rajiv Gandhi International Stadium, Uppal                              Hyderabad         1.00
Rajiv Gandhi International Stadium, Uppal, Hyderabad                   Hyderabad         1.00
MA Chidambaram Stadium, Chepauk, Chennai                               Chennai           1.00
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur     Mohali            1.00
Maharashtra Cricket Association Stadium                                Pune              1.00
Maharashtra Cricket Association Stadium, Pune                          Pune              1.00
Narendra Modi Stadium, Ahmedabad                                       Ahmedabad         1.00
Nehru Stadium                                                          Kochi             1.00
New Wanderers Stadium                                                  Johannesburg      1.00
Newlands                                                               Cape Town         1.00
OUTsurance Oval                                                        Bloemfontein      1.00
Punjab Cricket Association IS Bindra Stadium                           Chandigarh        1.00
Punjab Cricket Association IS Bindra Stadium, Mohali                   Chandigarh        1.00
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh       Chandigarh        1.00
Punjab Cricket Association Stadium, Mohali                             Chandigarh        1.00
Rajiv Gandhi International Stadium                                     Hyderabad         1.00
Sheikh Zayed Stadium                                                   Abu Dhabi         1.00
St George's Park                                                       Port Elizabeth    1.00
Sardar Patel Stadium, Motera                                           Ahmedabad         1.00
Saurashtra Cricket Association Stadium                                 Rajkot            1.00
Sawai Mansingh Stadium                                                 Jaipur            1.00
Sawai Mansingh Stadium, Jaipur                                         Jaipur            1.00
Shaheed Veer Narayan Singh International Stadium                       Raipur            1.00
Sharjah Cricket Stadium                                                Sharjah           1.00
Vidarbha Cricket Association Stadium, Jamtha                           Nagpur            1.00
Wankhede Stadium                                                       Mumbai            1.00
Subrata Roy Sahara Stadium                                             Pune              1.00
SuperSport Park                                                        Centurion         1.00
Wankhede Stadium, Mumbai                                               Mumbai            1.00
Zayed Cricket Stadium, Abu Dhabi                                       Abu Dhabi         1.00
Dr DY Patil Sports Academy, Mumbai                                     Mumbai            0.55
                                                                       Navi Mumbai       0.45
Name: proportion, dtype: float64

## Observation 1- Multiple Venues are listed duplicated, some are renames and some are duplicated due to city name along with their names, we will standardise this.

In [294]:
ipl_df.value_counts("city")

city
Mumbai            173
Kolkata            93
Delhi              90
Chennai            85
Hyderabad          77
Bangalore          65
Chandigarh         61
Jaipur             57
Pune               51
Abu Dhabi          37
Ahmedabad          36
Bengaluru          29
Visakhapatnam      15
Durban             15
Lucknow            14
Dubai              13
Dharamsala         13
Centurion          12
Rajkot             10
Sharjah            10
Indore              9
Navi Mumbai         9
Johannesburg        8
Ranchi              7
Cape Town           7
Port Elizabeth      7
Cuttack             7
Raipur              6
Mohali              5
Kochi               5
Kanpur              4
Guwahati            3
Nagpur              3
East London         3
Kimberley           3
Bloemfontein        2
Name: count, dtype: int64

## Observation 2 - Some City names are duplicated like Bengaluru and Banglore, we will standardise this as well.

In [295]:
ipl_df.value_counts("team1")

team1
Royal Challengers Bangalore    135
Chennai Super Kings            128
Mumbai Indians                 123
Kolkata Knight Riders          121
Rajasthan Royals               101
Kings XI Punjab                 92
Sunrisers Hyderabad             86
Delhi Daredevils                85
Delhi Capitals                  41
Deccan Chargers                 39
Punjab Kings                    31
Pune Warriors                   23
Lucknow Super Giants            23
Gujarat Titans                  21
Gujarat Lions                   16
Royal Challengers Bengaluru      9
Kochi Tuskers Kerala             7
Rising Pune Supergiant           7
Rising Pune Supergiants          7
Name: count, dtype: int64

## Observation 3 - Duplicates are caused here by:
  

*   Some team name changes like Delhi Daredevils to Delhi Capitals, Royal Challengers Bengalore  to Royal Challengers Bengaluru
*   Rising Pune Supergiant and Rising Pune Supergiants , minor spelling change

In [296]:
ipl_df.value_counts("match_type")

match_type
League                1029
Final                   17
Qualifier 1             14
Qualifier 2             14
Eliminator              11
Semi Final               6
Elimination Final        3
3rd Place Play-Off       1
Name: count, dtype: int64

In [297]:
ipl_df.value_counts("method")

method
D/L    21
Name: count, dtype: int64

## Observation 4- Only one value of method - D/L, we will rather create one column like DL_used - Yes or No

In [298]:
# Null values analysis
null_city_rows = ipl_df[ipl_df['city'].isnull()]
null_method_rows = ipl_df[ipl_df['method'].isnull()]
null_winner_rows = ipl_df[ipl_df['winner'].isnull()]
null_result_margin_rows = ipl_df[ipl_df['result_margin'].isnull()]
null_player_of_match_rows = ipl_df[ipl_df['player_of_match'].isnull()]
null_target_runs_rows = ipl_df[ipl_df['target_runs'].isnull()]
null_target_overs_rows = ipl_df[ipl_df['target_overs'].isnull()]

display("1 ) null_city_rows")
display(null_city_rows)

display("2 ) null_method_rows")
display(null_method_rows)

display("3 ) null_winner_rows")
display(null_winner_rows)

display("4) null_result_margin_rows")
display(null_result_margin_rows)

display("5 ) null_player_of_match_rows")
display(null_player_of_match_rows)

display("6 ) null_target_runs_rows")
display(null_target_runs_rows)

display("7 ) null_target_overs_rows")
display(null_target_overs_rows)

'1 ) null_city_rows'

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
399,729281,2014,NaN,2014-04-17,League,YS Chahal,Sharjah Cricket Stadium,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,8.0,146.0,20.0,N,NaN,Aleem Dar,S Ravi
402,729287,2014,NaN,2014-04-19,League,PA Patel,Dubai International Cricket Stadium,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,7.0,116.0,20.0,N,NaN,Aleem Dar,AK Chaudhary
403,729289,2014,NaN,2014-04-19,League,JP Duminy,Dubai International Cricket Stadium,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,Delhi Daredevils,wickets,4.0,167.0,20.0,N,NaN,Aleem Dar,VA Kulkarni
404,729291,2014,NaN,2014-04-20,League,GJ Maxwell,Sharjah Cricket Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,7.0,192.0,20.0,N,NaN,BF Bowden,M Erasmus
406,729295,2014,NaN,2014-04-22,League,GJ Maxwell,Sharjah Cricket Stadium,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kings XI Punjab,runs,72.0,194.0,20.0,N,NaN,M Erasmus,S Ravi
407,729297,2014,NaN,2014-04-23,League,RA Jadeja,Dubai International Cricket Stadium,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals,field,Chennai Super Kings,runs,7.0,141.0,20.0,N,NaN,HDPK Dharmasena,RK Illingworth
408,729299,2014,NaN,2014-04-24,League,CA Lynn,Sharjah Cricket Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,2.0,151.0,20.0,N,NaN,Aleem Dar,VA Kulkarni
409,729301,2014,NaN,2014-04-25,League,AJ Finch,Dubai International Cricket Stadium,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,4.0,185.0,20.0,N,NaN,M Erasmus,S Ravi
410,729303,2014,NaN,2014-04-25,League,MM Sharma,Dubai International Cricket Stadium,Chennai Super Kings,Mumbai Indians,Mumbai Indians,bat,Chennai Super Kings,wickets,7.0,142.0,20.0,N,NaN,BF Bowden,M Erasmus
413,729309,2014,NaN,2014-04-27,League,M Vijay,Sharjah Cricket Stadium,Delhi Daredevils,Mumbai Indians,Mumbai Indians,bat,Delhi Daredevils,wickets,6.0,126.0,20.0,N,NaN,Aleem Dar,VA Kulkarni
414,729311,2014,NaN,2014-04-27,League,DR Smith,Sharjah Cricket Stadium,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Chennai Super Kings,wickets,5.0,146.0,20.0,N,NaN,AK Chaudhary,VA Kulkarni
415,729313,2014,NaN,2014-04-28,League,Sandeep Sharma,Dubai International Cricket Stadium,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab,field,Kings XI Punjab,wickets,5.0,125.0,20.0,N,NaN,BF Bowden,S Ravi
417,729317,2014,NaN,2014-04-30,League,B Kumar,Dubai International Cricket Stadium,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,field,Sunrisers Hyderabad,runs,15.0,173.0,20.0,N,NaN,HDPK Dharmasena,M Erasmus
757,1216493,2020,NaN,2020-09-20,League,MP Stoinis,Dubai International Cricket Stadium,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,Delhi Capitals,tie,NaN,158.0,20.0,Y,NaN,AK Chaudhary,Nitin Menon
758,1216534,2020,NaN,2020-09-21,League,YS Chahal,Dubai International Cricket Stadium,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Royal Challengers Bangalore,runs,10.0,164.0,20.0,N,NaN,AY Dandekar,Nitin Menon
759,1216496,2020,NaN,2020-09-22,League,SV Samson,Sharjah Cricket Stadium,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,field,Rajasthan Royals,runs,16.0,217.0,20.0,N,NaN,C Shamshuddin,VA Kulkarni
761,1216510,2020,NaN,2020-09-24,League,KL Rahul,Dubai International Cricket Stadium,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kings XI Punjab,runs,97.0,207.0,20.0,N,NaN,AK Chaudhary,PR Reiffel
762,1216539,2020,NaN,2020-09-25,League,PP Shaw,Dubai International Cricket Stadium,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,Delhi Capitals,runs,44.0,176.0,20.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
764,1216527,2020,NaN,2020-09-27,League,SV Samson,Sharjah Cricket Stadium,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,224.0,20.0,N,NaN,RK Illingworth,K Srinivasan
765,1216547,2020,NaN,2020-09-28,League,AB de Villiers,Dubai International Cricket Stadium,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,202.0,20.0,Y,NaN,Nitin Menon,PR Reiffel
767,1216504,2020,NaN,2020-09-30,League,Shivam Mavi,Dubai International Cricket Stadium,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Kolkata Knight Riders,runs,37.0,175.0,20.0,N,NaN,KN Ananthapadmanabhan,C Shamshuddin
769,1216516,2020,NaN,2020-10-02,League,PK Garg,Dubai International Cricket Stadium,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,7.0,165.0,20.0,N,NaN,AK Chaudhary,PR Reiffel
771,1216515,2020,NaN,2020-10-03,League,SS Iyer,Sharjah Cricket Stadium,Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,Delhi Capitals,runs,18.0,229.0,20.0,N,NaN,VA Kulkarni,RK Illingworth
772,1216513,2020,NaN,2020-10-04,League,SR Watson,Dubai International Cricket Stadium,Kings XI Punjab,Chennai Super Kings,Kings XI Punjab,bat,Chennai Super Kings,wickets,10.0,179.0,20.0,N,NaN,AY Dandekar,Nitin Menon
773,1216538,2020,NaN,2020-10-04,League,TA Boult,Sharjah Cricket Stadium,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,Mumbai Indians,runs,34.0,209.0,20.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
774,1216519,2020,NaN,2020-10-05,League,AR Patel,Dubai International Cricket Stadium,Delhi Capitals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Delhi Capitals,runs,59.0,197.0,20.0,N,NaN,Nitin Menon,YC Barde
777,1216542,2020,NaN,2020-10-08,League,JM Bairstow,Dubai International Cricket Stadium,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,69.0,202.0,20.0,N,NaN,AK Chaudhary,Nitin Menon
778,1216500,2020,NaN,2020-10-09,League,R Ashwin,Sharjah Cricket Stadium,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,field,Delhi Capitals,runs,46.0,185.0,20.0,N,NaN,KN Ananthapadmanabhan,C Shamshuddin
780,1216525,2020,NaN,2020-10-10,League,V Kohli,Dubai International Cricket Stadium,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,37.0,170.0,20.0,N,NaN,AK Chaudhary,PR Reiffel
781,1216507,2020,NaN,2020-10-11,League,R Tewatia,Dubai International Cricket Stadium,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,bat,Rajasthan Royals,wickets,5.0,159.0,20.0,N,NaN,YC Barde,PR Reiffel
783,1216540,2020,NaN,2020-10-12,League,AB de Villiers,Sharjah Cricket Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,82.0,195.0,20.0,N,NaN,RK Illingworth,K Srinivasan
784,1216528,2020,NaN,2020-10-13,League,RA Jadeja,Dubai International Cricket Stadium,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,bat,Chennai Super Kings,runs,20.0,168.0,20.0,N,NaN,AK Chaudhary,PR Reiffel
785,1216543,2020,NaN,2020-10-14,League,A Nortje,Dubai International Cricket Stadium,Delhi Capitals,Rajasthan Royals,Delhi Capitals,bat,Delhi Capitals,runs,13.0,162.0,20.0,N,NaN,AK Chaudhary,Nitin Menon
786,1216531,2020,NaN,2020-10-15,League,KL Rahul,Sharjah Cricket Stadium,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,wickets,8.0,172.0,20.0,N,NaN,KN Ananthapadmanabhan,C Shamshuddin
788,1216509,2020,NaN,2020-10-17,League,S Dhawan,Sharjah Cricket Stadium,Chennai Super Kings,Delhi Capitals,Chennai Super Kings,bat,Delhi Capitals,wickets,5.0,180.0,20.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
789,1216522,2020,NaN,2020-10-17,League,AB de Villiers,Dubai International Cricket Stadium,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,bat,Royal Challengers Bangalore,wickets,7.0,178.0,20.0,N,NaN,AK Chaudhary,Nitin Menon
791,1216517,2020,NaN,2020-10-18,League,KL Rahul,Dubai International Cricket Stadium,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,Kings XI Punjab,tie,NaN,177.0,20.0,Y,NaN,Nitin Menon,PR Reiffel
793,1216546,2020,NaN,2020-10-20,League,S Dhawan,Dubai International Cricket Stadium,Delhi Capitals,Kings XI Punjab,Delhi Capitals,bat,Kings XI Punjab,wickets,5.0,165.0,20.0,N,NaN,C Shamshuddin,RK Illingworth
795,1216518,2020,NaN,2020-10-22,League,MK Pandey,Dubai International Cricket Stadium,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,8.0,155.0,20.0,N,NaN,Nitin Menon,PR Reiffel
796,1216521,2020,NaN,2020-10-23,League,TA Boult,Sharjah Cricket Stadium,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,10.0,115.0,20.0,N,NaN,C Shamshuddin,VA Kulkarni
798,1216498,2020,NaN,2020-10-24,League,CJ Jordan,Dubai International Cricket Stadium,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kings XI Punjab,runs,12.0,127.0,20.0,N,NaN,AY Dandekar,PR Reiffel
800,1216544,2020,NaN,2020-10-25,League,RD Gaikwad,Dubai International Cricket Stadium,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Chennai Super Kings,wickets,8.0,146.0,20.0,N,NaN,C Shamshuddin,RK Illingworth
801,1216520,2020,NaN,2020-10-26,League,CH Gayle,Sharjah Cricket Stadium,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,8.0,150.0,20.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
802,1216524,2020,NaN,2020-10-27,League,WP Saha,Dubai International Cricket Stadium,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Sunrisers Hyderabad,runs,88.0,220.0,20.0,N,NaN,AK Chaudhary,Nitin Menon
804,1216536,2020,NaN,2020-10-29,League,RD Gaikwad,Dubai International Cricket Stadium,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,6.0,173.0,20.0,N,NaN,C Shamshuddin,RK Illingworth
806,1216502,2020,NaN,2020-10-31,League,Sandeep Sharma,Sharjah Cricket Stadium,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,5.0,121.0,20.0,N,NaN,KN Ananthapadmanabhan,K Srinivasan
807,1216535,2020,NaN,2020-10-31,League,Ishan Kishan,Dubai International Cricket Stadium,Delhi Capitals,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,9.0,111.0,20.0,N,NaN,YC Barde,PR Reiffel
809,1216530,2020,NaN,2020-11-01,League,PJ Cummins,Dubai International Cricket Stadium,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Kolkata Knight Riders,runs,60.0,192.0,20.0,N,NaN,Nitin Menon,PR Reiffel
811,1216495,2020,NaN,2020-11-03,League,S Nadeem,Sharjah Cricket Stadium,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,10.0,150.0,20.0,N,NaN,C Shamshuddin,RK Illingworth
812,1237177,2020,NaN,2020-11-05,Qualifier 1,JJ Bumrah,Dubai International Cricket Stadium,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,201.0,20.0,N,NaN,CB Gaffaney,Nitin Menon
815,1237181,2020,NaN,2020-11-10,Final,TA Boult,Dubai International Cricket Stadium,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,157.0,20.0,N,NaN,CB Gaffaney,Nitin Menon

'2 ) null_method_rows'

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2008,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2008,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2008,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2008,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2008,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

'3 ) null_winner_rows'

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
241,501265,2011,Delhi,2011-05-21,League,NaN,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,no result,NaN,NaN,NaN,N,NaN,SS Hazare,RJ Tucker
485,829763,2015,Bangalore,2015-04-29,League,NaN,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,NaN,NaN,N,NaN,JD Cloete,PG Pathak
511,829813,2015,Bangalore,2015-05-17,League,NaN,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,NaN,no result,NaN,188.0,20.0,N,NaN,HDPK Dharmasena,K Srinivasan
744,1178424,2019,Bengaluru,2019-04-30,League,NaN,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,63.0,5.0,N,NaN,NJ Llong,UV Gandhe
994,1359519,2023,Lucknow,2023-05-03,League,NaN,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,NaN,no result,NaN,NaN,NaN,N,NaN,AK Chaudhary,NA Patwardhan

'4) null_result_margin_rows'

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
66,392190,2009,Cape Town,2009-04-23,League,YK Pathan,Newlands,Kolkata Knight Riders,Rajasthan Royals,Kolkata Knight Riders,field,Rajasthan Royals,tie,NaN,151.0,20.0,Y,NaN,MR Benson,M Erasmus
130,419121,2010,Chennai,2010-03-21,League,J Theron,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,field,Kings XI Punjab,tie,NaN,137.0,20.0,Y,NaN,K Hariharan,DJ Harper
241,501265,2011,Delhi,2011-05-21,League,NaN,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,no result,NaN,NaN,NaN,N,NaN,SS Hazare,RJ Tucker
328,598004,2013,Hyderabad,2013-04-07,League,GH Vihari,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Sunrisers Hyderabad,tie,NaN,131.0,20.0,Y,NaN,AK Chaudhary,S Ravi
342,598017,2013,Bangalore,2013-04-16,League,V Kohli,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,Royal Challengers Bangalore,tie,NaN,153.0,20.0,Y,NaN,M Erasmus,VA Kulkarni
416,729315,2014,Abu Dhabi,2014-04-29,League,JP Faulkner,Sheikh Zayed Stadium,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,bat,Rajasthan Royals,tie,NaN,153.0,20.0,Y,NaN,Aleem Dar,AK Chaudhary
475,829741,2015,Ahmedabad,2015-04-21,League,SE Marsh,"Sardar Patel Stadium, Motera",Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,tie,NaN,192.0,20.0,Y,NaN,M Erasmus,S Ravi
485,829763,2015,Bangalore,2015-04-29,League,NaN,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,NaN,NaN,N,NaN,JD Cloete,PG Pathak
511,829813,2015,Bangalore,2015-05-17,League,NaN,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,NaN,no result,NaN,188.0,20.0,N,NaN,HDPK Dharmasena,K Srinivasan
610,1082625,2017,Rajkot,2017-04-29,League,KH Pandya,Saurashtra Cricket Association Stadium,Gujarat Lions,Mumbai Indians,Gujarat Lions,bat,Mumbai Indians,tie,NaN,154.0,20.0,Y,NaN,AK Chaudhary,CB Gaffaney
705,1175365,2019,Delhi,2019-03-30,League,PP Shaw,Arun Jaitley Stadium,Kolkata Knight Riders,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,tie,NaN,186.0,20.0,Y,NaN,AY Dandekar,Nitin Menon
744,1178424,2019,Bengaluru,2019-04-30,League,NaN,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,63.0,5.0,N,NaN,NJ Llong,UV Gandhe
746,1178426,2019,Mumbai,2019-05-02,League,JJ Bumrah,Wankhede Stadium,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,Mumbai Indians,tie,NaN,163.0,20.0,Y,NaN,CK Nandan,S Ravi
757,1216493,2020,NaN,2020-09-20,League,MP Stoinis,Dubai International Cricket Stadium,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,Delhi Capitals,tie,NaN,158.0,20.0,Y,NaN,AK Chaudhary,Nitin Menon
765,1216547,2020,NaN,2020-09-28,League,AB de Villiers,Dubai International Cricket Stadium,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,202.0,20.0,Y,NaN,Nitin Menon,PR Reiffel
790,1216512,2020,Abu Dhabi,2020-10-18,League,LH Ferguson,Sheikh Zayed Stadium,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kolkata Knight Riders,tie,NaN,164.0,20.0,Y,NaN,PG Pathak,S Ravi
791,1216517,2020,NaN,2020-10-18,League,KL Rahul,Dubai International Cricket Stadium,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,Kings XI Punjab,tie,NaN,177.0,20.0,Y,NaN,Nitin Menon,PR Reiffel
835,1254077,2021,Chennai,2021-04-25,League,PP Shaw,"MA Chidambaram Stadium, Chepauk, Chennai",Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,tie,NaN,160.0,20.0,Y,NaN,CB Gaffaney,KN Ananthapadmanabhan
994,1359519,2023,Lucknow,2023-05-03,League,NaN,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,NaN,no result,NaN,NaN,NaN,N,NaN,AK Chaudhary,NA Patwardhan

'5 ) null_player_of_match_rows'

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
241,501265,2011,Delhi,2011-05-21,League,NaN,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,no result,NaN,NaN,NaN,N,NaN,SS Hazare,RJ Tucker
485,829763,2015,Bangalore,2015-04-29,League,NaN,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,NaN,NaN,N,NaN,JD Cloete,PG Pathak
511,829813,2015,Bangalore,2015-05-17,League,NaN,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,NaN,no result,NaN,188.0,20.0,N,NaN,HDPK Dharmasena,K Srinivasan
744,1178424,2019,Bengaluru,2019-04-30,League,NaN,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,63.0,5.0,N,NaN,NJ Llong,UV Gandhe
994,1359519,2023,Lucknow,2023-05-03,League,NaN,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,NaN,no result,NaN,NaN,NaN,N,NaN,AK Chaudhary,NA Patwardhan

'6 ) null_target_runs_rows'

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
241,501265,2011,Delhi,2011-05-21,League,NaN,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,no result,NaN,NaN,NaN,N,NaN,SS Hazare,RJ Tucker
485,829763,2015,Bangalore,2015-04-29,League,NaN,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,NaN,NaN,N,NaN,JD Cloete,PG Pathak
994,1359519,2023,Lucknow,2023-05-03,League,NaN,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,NaN,no result,NaN,NaN,NaN,N,NaN,AK Chaudhary,NA Patwardhan

'7 ) null_target_overs_rows'

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
241,501265,2011,Delhi,2011-05-21,League,NaN,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,no result,NaN,NaN,NaN,N,NaN,SS Hazare,RJ Tucker
485,829763,2015,Bangalore,2015-04-29,League,NaN,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,NaN,NaN,N,NaN,JD Cloete,PG Pathak
994,1359519,2023,Lucknow,2023-05-03,League,NaN,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,NaN,no result,NaN,NaN,NaN,N,NaN,AK Chaudhary,NA Patwardhan

## Observation 5 - Missing Values Explanation:


> a) Method
- 1074 values missing - This is expected as if match was played interrupted ,like rain, only then sometime D/L is applied, else method is null , what we can do maybe  change column to yes/no kind of column, like if_dl.



> b ) city

- 51 values missing - Data Error - Matches were Played in 2014 and 2020 in Sharjah , Abudhabi and Dubai International UAE, we can fill missing values as per city mapping
> c ) result_margin
- 19 values missing - Matches without result - either "Tie"(14) or "no result" (5) won't have any result margin. We can say value is 0 for "Tie" and keep -1 for those 5 "No Results" rows as noise
> d ) player_of_match
- 5 rows - "No result rows"
> e ) winner
- 5 rows - "No result rows" same as above      
>f ) target_runs
- "No result rows" where no overs could be played at all
>g ) target_over
- "No result rows" where no overs could be played at all

## Standardising Columns and Fixing Missing Values

In [299]:
import pandas as pd

# 1. Standardise differently listed Venue Names
standard_venues = {
    # Bengaluru
    "M.Chinnaswamy Stadium": "M Chinnaswamy Stadium",
    "M Chinnaswamy Stadium, Bengaluru": "M Chinnaswamy Stadium",

    # Chennai
    "MA Chidambaram Stadium, Chepauk": "MA Chidambaram Stadium",
    "MA Chidambaram Stadium, Chepauk, Chennai": "MA Chidambaram Stadium",

    # Delhi
    "Arun Jaitley Stadium, Delhi": "Arun Jaitley Stadium",
    "Feroz Shah Kotla": "Arun Jaitley Stadium",

    # Mumbai & Navi Mumbai
    "Wankhede Stadium, Mumbai": "Wankhede Stadium",
    "Brabourne Stadium, Mumbai": "Brabourne Stadium",
    "Dr DY Patil Sports Academy, Mumbai": "Dr DY Patil Sports Academy",

    # Chandigarh / Mohali
    "Punjab Cricket Association Stadium, Mohali": "Punjab Cricket Association IS Bindra Stadium",
    "Punjab Cricket Association IS Bindra Stadium, Mohali": "Punjab Cricket Association IS Bindra Stadium",
    "Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh": "Punjab Cricket Association IS Bindra Stadium",

    # Hyderabad
    "Rajiv Gandhi International Stadium, Uppal": "Rajiv Gandhi International Stadium",
    "Rajiv Gandhi International Stadium, Uppal, Hyderabad": "Rajiv Gandhi International Stadium",

    # Pune
    "Maharashtra Cricket Association Stadium, Pune": "Maharashtra Cricket Association Stadium",
    "Subrata Roy Sahara Stadium": "Maharashtra Cricket Association Stadium",

    # Ahmedabad
    "Narendra Modi Stadium, Ahmedabad": "Narendra Modi Stadium",
    "Sardar Patel Stadium, Motera": "Narendra Modi Stadium",

    # Kolkata
    "Eden Gardens, Kolkata": "Eden Gardens",

    # Jaipur
    "Sawai Mansingh Stadium, Jaipur": "Sawai Mansingh Stadium",

    # Dharamsala
    "Himachal Pradesh Cricket Association Stadium, Dharamsala": "Himachal Pradesh Cricket Association Stadium",

    # Visakhapatnam
    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam": "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium",

    # Abu Dhabi
    "Zayed Cricket Stadium, Abu Dhabi": "Sheikh Zayed Stadium",
    "Zayed Cricket Stadium": "Sheikh Zayed Stadium",

    #Comma Separated
    "Barsapara Cricket Stadium, Guwahati": "Barsapara Cricket Stadium",
    "Vidarbha Cricket Association Stadium, Jamtha": "Vidarbha Cricket Association Stadium",
    "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow": "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium"
}

# 2. Fix the city inconsistencies alongside the venue clean-up
standard_cities = {
    "Bangalore": "Bengaluru",
    "Navi Mumbai": "Mumbai"
}

# Step A: Clean up the trailing/leading whitespaces
ipl_df['venue'] = ipl_df['venue'].str.strip()
ipl_df['city'] = ipl_df['city'].str.strip()

# Step B: Map the duplicates to their standard names
ipl_df['venue'] = ipl_df['venue'].replace(standard_venues)
ipl_df['city'] = ipl_df['city'].replace(standard_cities)

# Step C: Fix the specific PCA Mohali city classification (from Chandigarh to Mohali)
ipl_df.loc[ipl_df['venue'] == 'Punjab Cricket Association IS Bindra Stadium', 'city'] = 'Mohali'
# Step D: Verifying unique counts now
cleaned_grouped = ipl_df.groupby("venue")["city"].value_counts().sort_values(ascending=False)
print(cleaned_grouped)

venue                                                               city
Wankhede Stadium                                                    Mumbai            118
M Chinnaswamy Stadium                                               Bengaluru          94
Eden Gardens                                                        Kolkata            93
Arun Jaitley Stadium                                                Delhi              90
MA Chidambaram Stadium                                              Chennai            85
Rajiv Gandhi International Stadium                                  Hyderabad          77
Punjab Cricket Association IS Bindra Stadium                        Mohali             61
Sawai Mansingh Stadium                                              Jaipur             57
Maharashtra Cricket Association Stadium                             Pune               51
Dr DY Patil Sports Academy                                          Mumbai             37
Sheikh Zayed Stadium                                                Abu Dhabi          37
Narendra Modi Stadium                                               Ahmedabad          36
Brabourne Stadium                                                   Mumbai             27
Kingsmead                                                           Durban             15
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                 Visakhapatnam      15
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium        Lucknow            14
Himachal Pradesh Cricket Association Stadium                        Dharamsala         13
Dubai International Cricket Stadium                                 Dubai              13
SuperSport Park                                                     Centurion          12
Saurashtra Cricket Association Stadium                              Rajkot             10
Sharjah Cricket Stadium                                             Sharjah            10
Holkar Cricket Stadium                                              Indore              9
New Wanderers Stadium                                               Johannesburg        8
Barabati Stadium                                                    Cuttack             7
Newlands                                                            Cape Town           7
JSCA International Stadium Complex                                  Ranchi              7
St George's Park                                                    Port Elizabeth      7
Shaheed Veer Narayan Singh International Stadium                    Raipur              6
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur  Mohali              5
Nehru Stadium                                                       Kochi               5
Green Park                                                          Kanpur              4
Barsapara Cricket Stadium                                           Guwahati            3
De Beers Diamond Oval                                               Kimberley           3
Buffalo Park                                                        East London         3
Vidarbha Cricket Association Stadium                                Nagpur              3
OUTsurance Oval                                                     Bloemfontein        2
Name: count, dtype: int64

In [300]:
# 1. Fix Team names inconsistencies  - mapping dictionary for IPL franchises:
standard_teams = {
    "Royal Challengers Bangalore": "Royal Challengers Bengaluru",
    "Delhi Daredevils": "Delhi Capitals",
    "Kings XI Punjab": "Punjab Kings",
    "Rising Pune Supergiants": "Rising Pune Supergiant",
}
# 1. Clean team name columns
ipl_df[['team1', 'team2', 'toss_winner', 'winner']] = ipl_df[['team1', 'team2', 'toss_winner', 'winner']].apply(lambda x: x.str.strip().replace(standard_teams))

# 2. Get value counts now
print(ipl_df[['team1', 'team2', 'toss_winner', 'winner']].apply(pd.Series.value_counts).sort_values(by='team1', ascending=False))

                             team1  team2  toss_winner  winner
Royal Challengers Bengaluru    144    111          121     123
Chennai Super Kings            128    110          122     138
Delhi Capitals                 126    126          130     115
Mumbai Indians                 123    138          143     144
Punjab Kings                   123    123          109     112
Kolkata Knight Riders          121    130          122     131
Rajasthan Royals               101    120          120     112
Sunrisers Hyderabad             86     96           88      88
Deccan Chargers                 39     36           43      29
Pune Warriors                   23     23           20      12
Lucknow Super Giants            23     21           19      24
Gujarat Titans                  21     24           22      28
Gujarat Lions                   16     14           15      13
Rising Pune Supergiant          14     16           13      15
Kochi Tuskers Kerala             7      7            8       6

In [301]:
# Initialize the venue to city mapping dictionary
venue_to_city_map = {}

# Manually add mappings for the UAE venues that have all missing cities in 2014 or 2020
venue_to_city_map['Sharjah Cricket Stadium'] = 'Sharjah'
venue_to_city_map['Dubai International Cricket Stadium'] = 'Dubai'
venue_to_city_map['Sheikh Zayed Stadium'] = 'Abu Dhabi'

# 2. Fill missing city values using the map
ipl_df['city'] = ipl_df['city'].fillna(ipl_df['venue'].map(venue_to_city_map))

# 3. Verify that there are no more missing values in the 'city' column
missing_cities_count = ipl_df['city'].isnull().sum()
print(f"Missing cities: {missing_cities_count}")

Missing cities: 0

In [302]:
# Convert date column to datetime format
ipl_df['date'] = pd.to_datetime(ipl_df['date'])
ipl_df['date'].dtype

dtype('<M8[ns]')

In [303]:
ipl_df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2008,Bengaluru,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bengaluru,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2008,Mohali,2008-04-19,League,MEK Hussey,Punjab Cricket Association IS Bindra Stadium,Punjab Kings,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2008,Delhi,2008-04-19,League,MF Maharoof,Arun Jaitley Stadium,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Capitals,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2008,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bengaluru,Mumbai Indians,bat,Royal Challengers Bengaluru,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2008,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [304]:
ipl_df.value_counts("result")

result
wickets      578
runs         498
tie           14
no result      5
Name: count, dtype: int64

In [305]:
# Split result_margin into result_margin_runs and result_margin_wickets as value is very different in case of wickets or run victory
ipl_df['result_margin_runs'] = np.where(
    ipl_df['result'] == "runs",
    ipl_df['result_margin'],
    np.nan
)
ipl_df['result_margin_wickets'] = np.where(
    ipl_df['result'] == "wickets",
    ipl_df['result_margin'],
    np.nan
)

# Display sample of the split columns
print(ipl_df[['result', 'result_margin', 'result_margin_runs', 'result_margin_wickets']].head())
#Drop the result_margin now
ipl_df.drop(columns=['result_margin'], inplace=True)

    result  result_margin  result_margin_runs  result_margin_wickets
0     runs          140.0               140.0                    NaN
1     runs           33.0                33.0                    NaN
2  wickets            9.0                 NaN                    9.0
3  wickets            5.0                 NaN                    5.0
4  wickets            5.0                 NaN                    5.0

### Note - Though this has created NaNs, we need it by design, if I give 0 , it will impact average.

In [306]:
#Handling D/L flag:
ipl_df['is_dl']=np.where(ipl_df['method'].isnull(),0,1)
ipl_df.drop(columns=['method'], inplace=True)
ipl_df['is_dl'].value_counts()

is_dl
0    1074
1      21
Name: count, dtype: int64

In [307]:
# Compare D/L flag against shortened matches
pd.crosstab(ipl_df['is_dl'], ipl_df['target_overs'] < 20,
            rownames=['is_dl'], colnames=['shortened'])

shortened  False  True
is_dl
0           1065      9
1              0     21

In [308]:
ipl_df['is_shortened'] = np.where(ipl_df['target_overs'] < 20, 1, 0)

In [309]:
# match_importance: league / playoff / final
ipl_df['match_importance'] = np.where(
    ipl_df['match_type'] == 'League', 'league',
    np.where(ipl_df['match_type'] == 'Final', 'final', 'playoff')
)
ipl_df['match_importance'].value_counts()

match_importance
league     1029
playoff      49
final        17
Name: count, dtype: int64

In [310]:
#Assigning Season Phase to Early, Mid or late, idea is to bin them as per their number of days into the season.
# Sort by date and id in case two matches share a date
ipl_df = ipl_df.sort_values(['date', 'id']).reset_index(drop=True)

# Match number within each season
ipl_df['match_number'] = ipl_df.groupby('season').cumcount() + 1

# Split each season into 3 equal-count bins: 0 = early, 1 = mid, 2 = late
phase = ipl_df.groupby('season')['match_number'].transform(
    lambda x: pd.qcut(x, q=3, labels=False)
)
ipl_df['season_phase'] = phase.map({0: 'early', 1: 'mid', 2: 'late'})

# Check: each season should be split roughly into thirds
pd.crosstab(ipl_df['season'], ipl_df['season_phase'])

season_phase  early  late  mid
season
2008             19    20   19
2009             19    19   19
2010             20    20   20
2011             24    25   24
2012             25    25   24
2013             25    26   25
2014             20    20   20
2015             20    20   19
2016             20    20   20
2017             20    20   19
2018             20    20   20
2019             20    20   20
2020             20    20   20
2021             20    20   20
2022             25    25   24
2023             25    25   24
2024             24    24   23

In [311]:
#Toss Advantage - Check if winner and toss winner are same
ipl_df['toss_advantage'] = np.where(
    ipl_df['winner'].isnull(), np.nan,
    np.where(ipl_df['toss_winner'] == ipl_df['winner'], 1, 0)
)

In [312]:
#Home Advantage Check
team_home_city = {
    # Franchises home team mapping some are  Multi-City / Alternate Home Grounds
    "Rajasthan Royals": ["Jaipur", "Guwahati"],
    "Punjab Kings": ["Mohali", "Dharamsala", "Indore", "Cuttack"],
    "Delhi Capitals": ["Delhi", "Visakhapatnam", "Raipur"],
    "Chennai Super Kings": ["Chennai", "Pune", "Ranchi"],
    "Royal Challengers Bengaluru": ["Bengaluru"],
    "Mumbai Indians": ["Mumbai"],
    "Kolkata Knight Riders": ["Kolkata"],
    "Sunrisers Hyderabad": ["Hyderabad"],
    "Lucknow Super Giants": ["Lucknow"],
    "Gujarat Titans": ["Ahmedabad"],
    "Deccan Chargers": ["Hyderabad", "Visakhapatnam"],
    "Gujarat Lions": ["Rajkot", "Kanpur"],
    "Pune Warriors": ["Pune"],
    "Rising Pune Supergiant": ["Pune"],
    "Kochi Tuskers Kerala": ["Kochi"]
}
def is_home(team, city):
    return int(city in team_home_city.get(team, []))

ipl_df['team1_home'] = ipl_df.apply(lambda r: is_home(r['team1'], r['city']), axis=1)
ipl_df['team2_home'] = ipl_df.apply(lambda r: is_home(r['team2'], r['city']), axis=1)

In [313]:
# A match can't be home for both teams
both_home = ipl_df[(ipl_df['team1_home'] == 1) & (ipl_df['team2_home'] == 1)]
both_home[['season', 'city', 'team1', 'team2']]

     season  city          team1                team2
263    2012  Pune  Pune Warriors  Chennai Super Kings
363    2013  Pune  Pune Warriors  Chennai Super Kings

In [314]:
#In 2012 and 2013, Pune was home for Pune Warriors, not for CSK. CSK only used Pune as a home ground in 2018.

#Fix - Treat Pune as a CSK home city only in 2018:
csk_pune_not_home = (ipl_df['city'] == 'Pune') & (ipl_df['season'] != 2018)
ipl_df.loc[csk_pune_not_home & (ipl_df['team1'] == 'Chennai Super Kings'), 'team1_home'] = 0
ipl_df.loc[csk_pune_not_home & (ipl_df['team2'] == 'Chennai Super Kings'), 'team2_home'] = 0

#Check again:
both_home = ipl_df[(ipl_df['team1_home'] == 1) & (ipl_df['team2_home'] == 1)]
both_home[['season', 'city', 'team1', 'team2']]

Empty DataFrame
Columns: [season, city, team1, team2]
Index: []

In [315]:
# How many teams were "at home" in each match: 0, 1
home_count = ipl_df['team1_home'] + ipl_df['team2_home']

pd.crosstab(ipl_df['season'], home_count,
            rownames=['season'], colnames=['home_teams'])

home_teams   0   1
season
2008         3  55
2009        57   0
2010        11  49
2011         9  64
2012         4  70
2013         6  70
2014        27  33
2015        14  45
2016         6  54
2017         3  56
2018         2  58
2019         1  59
2020        60   0
2021        60   0
2022        62  12
2023         1  73
2024         4  67

## Observation 6 – Home advantage
Home cities are mapped per franchise, including secondary grounds (e.g. Punjab Kings at Dharamsala/Indore, Rajasthan Royals at Guwahati). A season-specific exception is applied for Chennai Super Kings in Pune, which was a CSK home ground only in 2018. In 2012–13 it belonged to Pune Warriors.
2009 (South Africa), 2020 (UAE) and 2021 are neutral seasons, so no team is marked as home. The 2021 result comes from the data itself, since teams didn't play in their home cities.
2022 was officially held at neutral venues in Mumbai and Pune, but Mumbai Indians' matches in Mumbai are kept as home games, on the assumption that a familiar city and crowd still give some advantage.
Limitation: a small number of league matches may be misclassified where a team used a secondary home ground missing from the mapping. Given how few matches this affects out of 1,095, the impact on the analysis is expected to be minimal.

## Venue Mapping